org.gradle.jvmargs=-Xmx4g -Dfile.encoding=utf-8
org.gradle.java.home=C:\\Program Files\\Eclipse Adoptium\\jdk-21.0.11.10-hotspot
org.gradle.daemon.idletimeout=3600000
systemProp.http.connectionTimeout=60000
systemProp.http.socketTimeout=60000
systemProp.https.connectionTimeout=60000
systemProp.https.socketTimeout=60000